#!/bin/bash

source $(dirname $0)/pdf2common

VERSION="0.0.1"
FORMAT='pdf:draw_pdf_Export:{"SelectPdfVersion":{"type":"long","value":"3"}}'
DIRMADE=false
UPOLICY="skip"
DEBUG=false
METASEP=", "

INFILE=""
INPUT=""
OUTPUT=""

if [ "$1" == "" ]; then
	exit
fi
while [ "$1" != "" ]; do
	PARAM=`echo $1 | awk -F= '{print $1}'`
	VALUE=`echo $1 | awk -F= '{print $2}'`
	case $PARAM in
		-h | --help)
			echo -e "\\nVisit project repo: https://github.com/Kuszki/pdf2archive\\n"
			exit
			;;
		-v | --version)
			echo $VERSION
			exit
			;;
		--debug)
			DEBUG=true
			MSGOPTS=""
			;;
		--cleanmetadata)
			PDFTITLE=""
			PDFAUTHOR=""
			PDFSUBJECT=""
			PDFKEYWORDS=""
			PDFCREATOR=""
			;;
		--title)
			PDFTITLE=$VALUE
			;;
		--author)
			PDFAUTHOR=$VALUE
			;;
		--subject)
			PDFSUBJECT=$VALUE
			;;
		--keywords)
			PDFKEYWORDS=$VALUE
			;;
		--creator)
			PDFCREATOR=$VALUE
			;;
		--good)
			DONE_FILE=$VALUE
			;;
		--bad)
			BAD_FILE=$VALUE
			;;
		--pass)
			PASS_FILE=$VALUE
			;;
		--validate)
			VALIDATE=$VALUE
			;;
		--upolicy)
			UPOLICY=$VALUE
			;;
		--sep)
			METASEP=$VALUE
			;;
		*.pdf)
			if [ "$INPUT" == "" ]; then
				INPUT=$PARAM
			elif [ "$OUTPUT" == "" ]; then
				OUTPUT=$PARAM
			else
				echo "ERROR: too many PDF files as input!"
				exit 1
			fi
			;;
		*)
			echo "ERROR: unknown parameter \"$PARAM\""
			exit 1
			;;
	esac
	shift
done

#=====# SET UP ALL THE STUFF #=====#

TMPDIRRR=$(mktemp -d -p /dev/shm/ XXXXXXXXXXXX.dir)
OUTDIR=$(dirname "${OUTPUT}")
INFILE=$(basename "${INPUT}")
TMPOUT="$TMPDIRRR/$INFILE"

if [ "$OUTPUT" == "" ]; then
	OUTPUT="${INPUT%.pdf}-PDFA.pdf"
fi

if [ ! -f "$INPUT" ]; then

	log_pass
	exit 1

fi

if [ -f "$OUTPUT" ]; then

	[ "$UPOLICY" == "skip" ] && exit 0
	[ "$UPOLICY" == "overwrite" ] && rm "$OUTPUT"

fi

METADUMP=$(pdfinfo "$INPUT")

[ -z ${PDFTITLE+x} ] && PDFTITLE=$(echo "$METADUMP" | grep "^Title:" | sed "s/^Title:\\s*//")
[ -z ${PDFAUTHOR+x} ] && PDFAUTHOR=$(echo "$METADUMP" | grep "^Author:" | sed "s/^Author:\\s*//")
[ -z ${PDFSUBJECT+x} ] && PDFSUBJECT=$(echo "$METADUMP" | grep "^Subject:" | sed "s/^Subject:\\s*//")
[ -z ${PDFKEYWORDS+x} ] && PDFKEYWORDS=$(echo "$METADUMP" | grep "^Keywords:" | sed "s/^Keywords:\\s*//")
[ -z ${PDFCREATOR+x} ] && PDFCREATOR=$(echo "$METADUMP" | grep "^Creator:" | sed "s/^Creator:\\s*//")

if $DEBUG; then
	echo "  DEBUG: running PDF2LIBRE, version $VERSION"
	echo "  DEBUG: using Libreoffice binary at $(which libreoffice), version $(libreoffice --version)"
	echo "  DEBUG: the input file is '$INPUT'"
	echo "  DEBUG: the output file is '$OUTPUT'"
	echo "  DEBUG: PDF title '$PDFTITLE'"
	echo "  DEBUG: PDF author '$PDFAUTHOR'"
	echo "  DEBUG: PDF subject '$PDFSUBJECT'"
	echo "  DEBUG: PDF keywords '$PDFKEYWORDS'"
	echo "  DEBUG: PDF creator '$PDFCREATOR'"
fi

if [ ! -d "$OUTDIR" ]; then
	mkdir -p "$OUTDIR" && DIRMADE=true

	if [ $? != 0 ]; then
		log_bad
		exit 1
	fi
fi

run libreoffice --headless \
	-env:UserInstallation="file://$TMPDIRRR" \
	--convert-to "$FORMAT" \
	--outdir "$TMPDIRRR" \
	 "$INPUT" && \
run exiftool -overwrite_original \
	-AllDates=now \
	-Title="$PDFTITLE" \
	-Producer="$PDFCREATOR" \
	-pdf:Subject="$PDFSUBJECT" \
	-pdf:Keywords="$PDFKEYWORDS" \
	-pdf:Author="$PDFAUTHOR" \
	-pdf:Creator="$PDFCREATOR" \
	-xmp:Subject="$PDFKEYWORDS" \
	-xmp:Description="$PDFSUBJECT" \
	-xmp:Creator="$PDFAUTHOR" \
	-xmp:CreatorTool="$PDFCREATOR" \
	-q -sep "$METASEP" "$TMPOUT" && \
cp "$TMPOUT" "$OUTPUT"

do_finalize $? "$TMPOUT"

rm -R "$TMPDIRRR"
