#!/bin/bash

source $(dirname $0)/pdf2common

VERSION="0.0.1"
INFILE=""
INPUT=""
METASEP=", "
DEBUG=false

#=====# INPUT PARSER #=====#
if [ "$1" == "" ]; then
	exit
fi
while [ "$1" != "" ]; do
	PARAM=`echo $1 | awk -F= '{print $1}'`
	VALUE=`echo $1 | awk -F= '{print $2}'`
	case $PARAM in
		-h | --help)
			echo -e "\\nVisit project repo: https://github.com/Kuszki/pdf2archive\\n"
			exit
			;;
		-v | --version)
			echo $VERSION
			exit
			;;
		--debug)
			DEBUG=true
			MSGOPTS=""
			;;
		--validate)
			VALIDATE=$VALUE
			;;
		--cleanmetadata)
			PDFTITLE=""
			PDFAUTHOR=""
			PDFSUBJECT=""
			PDFKEYWORDS=""
			PDFCREATOR=""
			;;
		--title)
			PDFTITLE=$VALUE
			;;
		--author)
			PDFAUTHOR=$VALUE
			;;
		--subject)
			PDFSUBJECT=$VALUE
			;;
		--keywords)
			PDFKEYWORDS=$VALUE
			;;
		--creator)
			PDFCREATOR=$VALUE
			;;
		--good)
			DONE_FILE=$VALUE
			;;
		--bad)
			BAD_FILE=$VALUE
			;;
		--pass)
			PASS_FILE=$VALUE
			;;
		--sep)
			METASEP=$VALUE
			;;
		*.pdf)
			if [ "$INPUT" == "" ]; then
				INPUT=$PARAM
			else
				echo "ERROR: too many PDF files as input!"
				exit 1
			fi
			;;
		*)
			echo "ERROR: unknown parameter \"$PARAM\""
			exit 1
			;;
	esac
	shift
done

INFILE=$(basename "${INPUT}")

if [ ! -f "$INPUT" ]; then

	log_pass
	exit 1

fi

METADUMP=$(pdfinfo "$INPUT")

[ -z ${PDFTITLE+x} ] && PDFTITLE=$(echo "$METADUMP" | grep "^Title:" | sed "s/^Title:\\s*//")
[ -z ${PDFAUTHOR+x} ] && PDFAUTHOR=$(echo "$METADUMP" | grep "^Author:" | sed "s/^Author:\\s*//")
[ -z ${PDFSUBJECT+x} ] && PDFSUBJECT=$(echo "$METADUMP" | grep "^Subject:" | sed "s/^Subject:\\s*//")
[ -z ${PDFKEYWORDS+x} ] && PDFKEYWORDS=$(echo "$METADUMP" | grep "^Keywords:" | sed "s/^Keywords:\\s*//")
[ -z ${PDFCREATOR+x} ] && PDFCREATOR=$(echo "$METADUMP" | grep "^Creator:" | sed "s/^Creator:\\s*//")

if $DEBUG; then
	echo "  DEBUG: running PDF2META, version $VERSION"
	echo "  DEBUG: using Exiftool binary at $(which exiftool), version $(exiftool -ver)"
	echo "  DEBUG: the input file is '$INPUT'"
	echo "  DEBUG: PDF title '$PDFTITLE'"
	echo "  DEBUG: PDF author '$PDFAUTHOR'"
	echo "  DEBUG: PDF subject '$PDFSUBJECT'"
	echo "  DEBUG: PDF keywords '$PDFKEYWORDS'"
	echo "  DEBUG: PDF creator '$PDFCREATOR'"
fi

run exiftool -overwrite_original \
	-AllDates=now \
	-Title="$PDFTITLE" \
	-Producer="$PDFCREATOR" \
	-pdf:Subject="$PDFSUBJECT" \
	-pdf:Keywords="$PDFKEYWORDS" \
	-pdf:Author="$PDFAUTHOR" \
	-pdf:Creator="$PDFCREATOR" \
	-xmp:Subject="$PDFKEYWORDS" \
	-xmp:Description="$PDFSUBJECT" \
	-xmp:Creator="$PDFAUTHOR" \
	-xmp:CreatorTool="$PDFCREATOR" \
	-q -sep "$METASEP" "$INPUT"

do_finalize $? "$INPUT"
